### ISSUE TITLE
f_coord_date_weather: Ajout du module d'extraction des données météo

### ISSUE THREAD

**Issue by romainlorrilliere** [cesco-lab/Vigie-Chiro_scripts#4]
données d'entrée : 
   table: longitude, latitude, date
   vecteur des taille de fenêtre
   localisation des fichier source des data météo

données sortie
  la table d'entrée avec nouvelle colonne de donnée météo (brut, anomalie, anomalie standardisé)

**Comment by YvesBas** [comment]
these are obsolete
